# Numpy 

# Numpy:Introduction

- NumPy is a Open Source Python package. It stands for **Numerical Python**. It is a library consisting of multidimensional array objects and a collection of routines for processing of array.

- NumPy is the fundamental package for scientific computing with Python , having following important functionalities: 
     - A powerful N-dimensional array object
     - A sophisticated (broadcasting) functions
     - Contains tools for integrating C/C++ and Fortran code
     - Have  useful  linear algebra, Fourier transform, and random number capabilities

### Why NuMpy?

- Mathematical and logical operations on **arrays**.

- Efficient storage and manipulation of **numerical arrays** is which is fundamental in  the process of  **data science**.

- NumPy arrays form the core of nearly the entire **ecosystem** of **data science** tools in Python,

In [1]:
import numpy as np

In [2]:
np.__version__

'1.24.3'

In [3]:
### NumPy's array class is know as ndarray.Even , it is known by the alias array

In [4]:
a =(1,2,3,4,5)

print(a)

(1, 2, 3, 4, 5)


In [5]:
type(a)

tuple

In [6]:
b= np.array(a)
print(b)

[1 2 3 4 5]


In [7]:
type(b)

numpy.ndarray

In [8]:
b.ndim # in order to find the dimsn

1

In [9]:
b.shape # no.of rows and no.columns

(5,)

In [10]:
b.size # total number of elements present in an array

5

In [11]:
b.dtype ## data type of my array

dtype('int32')

In [12]:
arr = np.array([[4,5,6],[7,8,9]])

In [13]:
print("Array elements are: ",arr)
print("Array is of type: ",type(arr))
print("No.of dimensions: ",arr.ndim)
print("Array shape: ",arr.shape)
print("Array size: ",arr.size)
print("Array stores elements of type: ",arr.dtype)

Array elements are:  [[4 5 6]
 [7 8 9]]
Array is of type:  <class 'numpy.ndarray'>
No.of dimensions:  2
Array shape:  (2, 3)
Array size:  6
Array stores elements of type:  int32


In [17]:
a =(1,2,3,4,5)
b =np.array(a)
print (b)

[1 2 3 4 5]


In [18]:
### Speed Comaprison numpy vs core python

In [19]:
import time as tm

size_1 = 1000000
def pure_python_version():
    start_time_pp =  tm.time() ## time of start of code execution
    list1 = range(size_1)
    list2 = range(size_1)
    sum_list=[list1[i]+list2[i] for i in range(len(list1))]
    end_time_pp =  tm.time()
    return end_time_pp - start_time_pp ## end time for execution (difference)

def numpy_version():
    start_time_np = tm.time()
    array1 = np.arange(size_1)
    array2 =  np.arange(size_1)
    sum_array = array1 + array2
    end_time_np = tm.time()
    return end_time_np - start_time_np ## end time for execution (difference)

python_time = pure_python_version()
numpy_time  = numpy_version()

print("pure python version=",python_time)
print("numpy =",numpy_time)

pure python version= 0.6386988162994385
numpy = 0.011652469635009766


In [20]:
my_list=[2,3,4,6,7,8]

In [21]:
my_array=np.array(my_list)
my_array

array([2, 3, 4, 6, 7, 8])

In [22]:
array_2 = [[1,2,3],[4,5,6],[7,8,9]]
array_3= np.array(array_2)
array_3
type(array_3)

numpy.ndarray

In [26]:
array_3.ndim

2

In [27]:
array_3.shape

(3, 3)

In [28]:
array_3.size

9

In [29]:
a = np.array([1, 2, 3,7,5,1], ndmin = 2) 
print (a)
np.ndim(a)

[[1 2 3 7 5 1]]


2

In [30]:
a = np.array([1, 2, 3], dtype = complex) 
print (a)

[1.+0.j 2.+0.j 3.+0.j]


In [31]:
a.dtype

dtype('complex128')

In [32]:
len(array_3) # total number of rows

3

In [33]:
len(a)

3

In [34]:
array_3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
array_3[2] #Indexing 3rd row

array([7, 8, 9])

In [36]:
array_3[0] 

array([1, 2, 3])

In [37]:
array_3[2,1]

8

In [38]:
array_3[2,0]

7

In [39]:
array_3[:,1] # Acessing Column

array([2, 5, 8])

In [42]:
array_3[:,0] 

array([1, 4, 7])

In [43]:
array_3[2:,:]

array([[7, 8, 9]])

In [44]:
array_3[2:,:1] ## 3rd row onwards until 1st column

array([[7]])

In [45]:
array_3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Array Atrributes
Numpy Arrays are conveinent and fast as compared to Python Lists.
1.Shape(no of rows & columns)

In [47]:
array_3.shape #Rows*Column

(3, 3)

### Array Initilization

In [48]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
np.arange(1,10,3) #(start,end,space)

array([1, 4, 7])

In [50]:
np.arange(1.8,10.4,3)

array([1.8, 4.8, 7.8])

In [51]:
np.zeros(3,dtype=int)

array([0, 0, 0])

In [52]:
np.zeros((3,2),dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [53]:
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [54]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [55]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__git_version__',
 '__loader__',

In [56]:
np.linspace(0,4,10) # (start,end,no of values)

array([0.        , 0.44444444, 0.88888889, 1.33333333, 1.77777778,
       2.22222222, 2.66666667, 3.11111111, 3.55555556, 4.        ])

In [57]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [58]:
np.linspace(0,10,1000)

array([ 0.        ,  0.01001001,  0.02002002,  0.03003003,  0.04004004,
        0.05005005,  0.06006006,  0.07007007,  0.08008008,  0.09009009,
        0.1001001 ,  0.11011011,  0.12012012,  0.13013013,  0.14014014,
        0.15015015,  0.16016016,  0.17017017,  0.18018018,  0.19019019,
        0.2002002 ,  0.21021021,  0.22022022,  0.23023023,  0.24024024,
        0.25025025,  0.26026026,  0.27027027,  0.28028028,  0.29029029,
        0.3003003 ,  0.31031031,  0.32032032,  0.33033033,  0.34034034,
        0.35035035,  0.36036036,  0.37037037,  0.38038038,  0.39039039,
        0.4004004 ,  0.41041041,  0.42042042,  0.43043043,  0.44044044,
        0.45045045,  0.46046046,  0.47047047,  0.48048048,  0.49049049,
        0.5005005 ,  0.51051051,  0.52052052,  0.53053053,  0.54054054,
        0.55055055,  0.56056056,  0.57057057,  0.58058058,  0.59059059,
        0.6006006 ,  0.61061061,  0.62062062,  0.63063063,  0.64064064,
        0.65065065,  0.66066066,  0.67067067,  0.68068068,  0.69

In [59]:
np.linspace(1.23,4.7,10) 

array([1.23      , 1.61555556, 2.00111111, 2.38666667, 2.77222222,
       3.15777778, 3.54333333, 3.92888889, 4.31444444, 4.7       ])

In [60]:
np.eye(3,4) # Identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [61]:
np.eye(6,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

### Array Initilization with Random numbers
In various applications( like assigning weights in Artificial Neural Networks) arrays need to be initialised randomly.
for this purpose there are various predefined functions in Numpy(reshape and random)

In [64]:
np.random.rand(2)

array([0.60065047, 0.93057687])

In [66]:
np.random.rand(2,2)

array([[0.60161237, 0.03687644],
       [0.20426715, 0.21892978]])

In [67]:
array_3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
array_3.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [70]:
array_3.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [71]:
arr1 =np.random.rand(9).reshape(3,3)

In [72]:
arr1

array([[0.67151566, 0.77366099, 0.50083915],
       [0.94766489, 0.31031665, 0.13142636],
       [0.68783706, 0.18212456, 0.15389364]])

In [73]:
arr1.ndim

2

### Indexing arrays

In [74]:
array_1 = np.arange(1,15)
array_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [75]:
array_1[2]

3

In [76]:
array_1[2:6]

array([3, 4, 5, 6])

In [77]:
array_1[-3]

12

In [78]:
array_1[:-3] # before values

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [79]:
array_1[2:6] = 8 #mutable i.e to change the member value of array

In [80]:
array_1

array([ 1,  2,  8,  8,  8,  8,  7,  8,  9, 10, 11, 12, 13, 14])

In [81]:
array_2=[[1,2,3],[4,5,6],[7,8,9]]
array_2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [82]:
np.array(array_2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:
np.eye(4,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.]])

In [84]:
a=[[1,2,3],[4,5,6],[8,8,9]]
z=np.array(a)
a

[[1, 2, 3], [4, 5, 6], [8, 8, 9]]

In [85]:
x=[[1,2,3,4],[4,5,6,7],[7,8,9,10],[10,11,12,13]]
x=np.array(x)
x

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10],
       [10, 11, 12, 13]])

In [86]:
x.ndim

2

In [87]:
x.min() ## overrall minimum

1

In [88]:
x.max()

13

In [89]:
x.mean()

7.0

In [90]:
x.min(axis=0) ## minimum value column wise

array([1, 2, 3, 4])

In [91]:
x.min(axis=1)

array([ 1,  4,  7, 10])

In [92]:
x.max(axis=0) ## minimum value column wise

array([10, 11, 12, 13])

In [93]:
x.max(axis=1)

array([ 4,  7, 10, 13])

In [94]:
x.argmin() ## index of the minimum value 

0

In [95]:
x.argmax() ## index of the minimum value 

15

In [96]:
x.argmin(axis=0) #column wise

array([0, 0, 0, 0], dtype=int64)

In [97]:
x.argmax(axis=1) #column wise

array([3, 3, 3, 3], dtype=int64)

In [98]:
x

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10],
       [10, 11, 12, 13]])

In [99]:
x.reshape(1,16) # 1D to 2D 

array([[ 1,  2,  3,  4,  4,  5,  6,  7,  7,  8,  9, 10, 10, 11, 12, 13]])

In [100]:
x.reshape(8,2)

array([[ 1,  2],
       [ 3,  4],
       [ 4,  5],
       [ 6,  7],
       [ 7,  8],
       [ 9, 10],
       [10, 11],
       [12, 13]])

In [101]:
x.flatten() #2D to 1D

array([ 1,  2,  3,  4,  4,  5,  6,  7,  7,  8,  9, 10, 10, 11, 12, 13])

In [102]:
x.transpose()

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12],
       [ 4,  7, 10, 13]])

In [103]:
z=x.transpose()

In [106]:
z.transpose()

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10],
       [10, 11, 12, 13]])

In [113]:
z[1,2]

8

In [115]:
np.linspace(1,100,10) 

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [116]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [117]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])